name: Python Build

on:
  push:
    paths:
    - 'python/**'
    - 'src/**'
    - '.github/workflows/python_test.yml'
    - "!python/.gitignore"
    - "!python/pytest/**"
  pull_request:
    paths:
    - 'python/**'
    - 'src/**'
    - '.github/workflows/python_test.yml'
    - "!python/.gitignore"
    - "!python/pytest/**"
  workflow_dispatch:

jobs:
  Install-Test:
    name: Installation test for python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies for ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y bash
      - name: Install dependencies for macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install bash
      - name: Install dependencies for windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install swig mingw git
      - name: Install abess
        run: |
          python --version
          cd ./python
          # python setup.py install
          pip install .
      - name: A simple test
        run: |
          echo "import abess;print(abess.__version__);" > ./test.py
          python ./test.py
